# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a0bd23501e022b6b75026509bd777dd61d8e164760c82a63ca122ee3b4849c146dfe4103b07c9bc80eb6808d20a45f7a9a9e6e0555046cfe214a245f7a79ddc

test:
  secret_key_base: 9544dccbb64ae3a44c99ca8c13697ba42cbc5e72417bd3c67f3a9eb7a16239ef90c245ab354d3428935057ea3f2ac961001d6a2cf2b78e3926cfca32f70f1687

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
